<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE beans [
        <!ELEMENT beans (bean*)>
        <!ELEMENT bean (property*)>
        <!ELEMENT property (#PCDATA)>

        <!ATTLIST bean id ID #REQUIRED>
        <!ATTLIST bean class CDATA #IMPLIED>
        <!ATTLIST property name CDATA #IMPLIED>
        <!ATTLIST property ref IDREF #IMPLIED>
]>

<beans>
    <!--IOC, 设置 组件 和 实际类 的对应关系-->
    <!--对应关系，将path对应到controller-->
<!--
    <bean id="fruit" class="fruit.controllers.FruitController">
        &lt;!&ndash;表示属性,name为属性名,ref为指向的组件id,指明依赖关系&ndash;&gt;
        <property name="fruitService" ref="fruitService"/>
    </bean>
-->

    <!--DAO-->
    <bean id="userDAO" class="book.dao.impl.UserDAOImpl"/>
    <bean id="bookDAO" class="book.dao.impl.BookDAOImpl"/>
    <bean id="cartItemDAO" class="book.dao.impl.CartItemDAOImpl"/>
    <bean id="orderDAO" class="book.dao.impl.OrderDAOImpl"/>
    <bean id="orderItemDAO" class="book.dao.impl.OrderItemDAOImpl"/>
    
    <!--service-->
    <bean id="userService" class="book.service.impl.UserServiceImpl">
        <property name="userDAO" ref="userDAO"/>
    </bean>
    <bean id="bookService" class="book.service.impl.BookServiceImpl">
        <property name="bookDAO" ref="bookDAO"/>
    </bean>
    <bean id="cartItemService" class="book.service.impl.CartItemServiceImpl">
        <property name="cartItemDAO" ref="cartItemDAO"/>
        <property name="bookService" ref="bookService"/>
    </bean>
    <bean id="orderService" class="book.service.impl.OrderServiceImpl">
        <property name="orderDAO" ref="orderDAO"/>
        <property name="orderItemDAO" ref="orderItemDAO"/>
        <property name="cartItemDAO" ref="cartItemDAO"/>
    </bean>
    
    <!--controller-->
    <bean id="page" class="myssm.myspringmvc.PageController"/>
    <bean id="user" class="book.controller.UserController">
        <property name="userService" ref="userService"/>
        <property name="cartItemService" ref="cartItemService"/>
    </bean>
    <bean id="book" class="book.controller.BookController">
        <property name="bookService" ref="bookService"/>
    </bean>
    <bean id="cart" class="book.controller.CartController">
        <property name="cartItemService" ref="cartItemService"/>
    </bean>
    <bean id="order" class="book.controller.OrderController">
        <property name="orderService" ref="orderService"/>
        <property name="cartItemService" ref="cartItemService"/>
    </bean>

</beans>

<!--
XML:可扩展的标记语言
1 声明（必须在第一行）
2 DTD文档类型定义
3 XML正文
4 节点Node
  元素节点Element
  文本节点Text
-->